# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "Device-Studio-Manual"
# copyright = '2023, HONGZHIWEI TECHNOLOGY(SHANGHAI) CO.,LTD. All Rights Reserved.'
# author = 'HONGZHIWEI TECHNOLOGY(SHANGHAI) CO.,LTD'
copyright = "2023, HZWtech, SHANGHAI"
author = "Feifei Lu，Jianghui chen"

# The short X.Y version
version = "version：2023A"

# The full version, including alpha/beta/rc tags
# release = 'version：2022A'

numfig = True
numfig_format = {"figure": "fig. %s", "subfigure": "(%s)"}


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# extensions = [
# ]
extensions = ["sphinx_rtd_theme"]


# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

html_theme_options = {
    "font_family": '"Microsoft YaHei", Arial, sans-serif',
}

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"
html_logo = "_static/DeviceStudio_logo.png"
html_theme_options = {
    "logo_only": True,
    "display_version": True,
    "prev_next_buttons_location": "bottom",
    "style_external_links": False,
    "collapse_navigation": True,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "includehidden": True,
    "titles_only": False,
}
html_favicon = "_static/DeviceStudio.ico"
html_search_enabled = True

# Show download links in the RTD menu
html_show_sourcelink = False
html_context = {
    "display_github": False,
    "github_user": "",
    "github_repo": "",
    "github_version": "",
    "conf_py_path": "/source/",
    "source_suffix": ".rst",
    # Add download links to the RTD versions menu
    "downloads": [
        ("PDF", "//hzw-devicestudio-doc.readthedocs.io/_/downloads/en/latest/pdf/"),
        ("EPUB", "//hzw-devicestudio-doc.readthedocs.io/_/downloads/en/latest/epub/"),
    ],
    "show_rtd_downloads": True,
}


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

html_search_language = "en"

# Show last updated time in page footer
html_last_updated_fmt = "%Y-%m-%d %H:%M:%S"


# -- Options for LaTeX output ---------------------------------------------
latex_engine = "xelatex"
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    "papersize": "a4paper",
    # The font size ('10pt', '11pt' or '12pt').
    "pointsize": "12pt",
    # Latex figure (float) alignment
    "figure_align": "H",
    # Additional packages and font configuration
    "fontpkg": r"""
\usepackage{fontspec}
\defaultfontfeatures{Ligatures=TeX}
\setmainfont{DejaVu Sans}
""",
    # Preamble for Unicode and graphics support
    "preamble": r"""
\usepackage{float}
\usepackage{graphicx}
\setkeys{Gin}{width=\textwidth,height=\textheight,keepaspectratio}
\DeclareUnicodeCharacter{00A0}{\nobreakspace}
""",
    # Footer content
    "fncychap": r"\usepackage[Bjornstrup]{fncychap}",
    "printindex": r"\footnotesize\raggedright\printindex",
}
